[package]
name = "oblivion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.9.2"
rand = "0.8.0"
ring = "0.17.5"
sha2 = "0.10.8"
regex = "1.10.2"
base64 = "0.21.5"