[package]
name = "oblivion"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
elliptic-curve = { version = "0.13.8", features = ["sec1"] }
p256 = { version = "0.13.2", features = ["ecdh"] }
rand = "0.8.5"
ring = "0.17.5"
sha2 = "0.10.8"
scrypt = "0.11.0"
regex = "1.10.2"
serde_json = "1.0.108"

[lib]
name = "oblivion"
