[package]
name = "oblivion"
version = "1.1.0"
authors = ["苏向夜 <fu050409@163.com>"]
description = "Rust High Concurrency Implementation of Oblivion, an End-to-End Encryption Protocol Based on ECDHE Encryption Algorithm"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
elliptic-curve = { version = "0.13", features = ["sec1"] }
p256 = { version = "0.13", features = ["ecdh"] }
rand = "0.8"
ring = "0.17"
sha2 = "0.10"
scrypt = "0.11"
regex = "1"
serde_json = "1"
oblivion-codegen = { path = "oblivion-codegen" }
proc-macro2 = "1"
futures = "0.3"
thiserror = "1"
anyhow = "1.0"

pyo3 = { version = "0.20", optional = true }

[lib]
name = "oblivion"

[profile.release]
lto = true

[features]
python = ["pyo3"]
