[package]
name = "oblivion"
version = "2.0.0"
authors = ["苏向夜 <fu050409@163.com>"]
description = "Rust High Concurrency Implementation of Oblivion, an End-to-End Encryption Protocol Based on ECDHE Encryption Algorithm"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }

# Cryptography Algorithms
rand = "0.8"
ring = "0.17"
sha2 = "0.10"
scrypt = "0.11"
hkdf = "0.12.4"

# Utils
oblivion-codegen = { path = "oblivion-codegen" }
regex = "1"
serde_json = "1"
proc-macro2 = "1"
futures = "0.3"
thiserror = "1"
anyhow = "1.0"
colored = "2.1"
chrono = "0.4"

# Optional
pyo3 = { version = "0.20", optional = true }
elliptic-curve = { version = "0.13", features = ["sec1"], optional = true }
p256 = { version = "0.13", features = ["ecdh"], optional = true }

[lib]
name = "oblivion"

[[bin]]
name = "main"

[profile.release]
lto = true

[features]
unsafe = ["elliptic-curve", "p256"]
python = ["pyo3"]
